// Dictionnaire i18n pour l'interface utilisateur (distinct de la langue du CV/lettre).
// Usage : const t = useT();  →  t.nav.new, t.profile.identityTitle, etc.

export type UILang = "fr" | "en";

export const UI = {
  fr: {
    nav: {
      new: "Nouvelle candidature",
      ats: "Analyse ATS",
      cv: "Mon CV",
      letter: "Ma lettre",
      history: "Historique",
      profile: "Mon profil",
      settings: "Paramètres",
    },
    brand: "IA CV + lettres",
    footer: {
      version: "Version 1.0 · Confidentialité prioritaire",
      privacy:
        "Vos données sont traitées localement. Aucune information personnelle n'est transmise ou conservée.",
      contact: "Contactez-nous",
    },
    viewTitles: {
      new: "Nouvelle candidature",
      ats: "Analyse ATS",
      cv: "Mon CV",
      letter: "Ma lettre",
      history: "Historique des candidatures",
      settings: "Paramètres",
      profile: "Mon profil",
    },
    profileWarning: {
      title: "Configurez d'abord votre profil",
      desc: "La qualité de l'analyse en dépend. Cliquez sur",
      link: "Mon profil",
      desc2: "pour charger le profil démo ou créer le vôtre.",
    },
    newApp: {
      step1Title: "1. Votre CV",
      step1Desc: "PDF, DOCX, TXT. Vous pouvez aussi utiliser votre CV actuel.",
      step2Title: "2. L'offre d'emploi",
      step2Desc: "Collez le texte de l'offre, ou indiquez une URL.",
      urlPlaceholder: "https://… (LinkedIn, WTTJ, Indeed…)",
      fetchBtn: "Récupérer",
      offerPlaceholder: "Ou collez directement le texte de l'offre d'emploi…",
      charCount: (n: number) => `${n} caractères${n >= 80 ? " ✓" : " (min. 80)"}`,
      step3Title: "3. Cibles & tonalité",
      step3Desc: "Langue de sortie, entreprise, LinkedIn, ton CV et ton lettre.",
      outputLangLabel: "Langue du CV et de la lettre",
      outputLangDescFr: "CV et lettre en français naturel, titres de sections en français.",
      outputLangDescEn:
        "CV and cover letter will be written in fluent English, with native Anglo style and section titles.",
      targetCompanyLabel: "Entreprise cible",
      targetCompanyPlaceholder: "ex : Datadog, Doctolib, Société Générale…",
      linkedinLabel: "URL LinkedIn (optionnel)",
      linkedinPlaceholder: "https://www.linkedin.com/in/votre-profil",
      cvVersionLabel: "Version CV",
      letterToneLabel: "Ton de la lettre",
      launchBtn: "Lancer l'analyse ATS + CV + lettre",
      launchBtnShort: "Lancer l'analyse",
      analyzing: "Analyse en cours…",
      analyzingShort: "Analyse…",
      estimatedTime: "~20 secondes • analyse ATS + CV refondu + lettre + coach",
      newAnalysis: "Nouvelle analyse",
      badgeCv: (ready: boolean) => `CV ${ready ? "✓" : "—"}`,
      badgeOffer: (ready: boolean, n: number) => `Offre ${ready ? "✓" : `${n}/80`}`,
    },
    empty: {
      ats: "Lancez une analyse pour voir les scores ATS.",
      cv: "Aucun CV généré pour le moment.",
      letter: "Aucune lettre générée pour le moment.",
      startBtn: "Démarrer une analyse",
    },
    cvView: {
      tonalityLabel: "Tonalité",
      onePage: "· 1 page A4",
      templateTitle: "Template visuel",
      templateDesc: "Tous les templates sont single column et ATS safe.",
    },
    letterView: {
      tonLabel: "Ton",
    },
    settings: {
      storageTitle: "Stockage",
      storageDesc:
        "Tout est stocké localement dans votre navigateur. Aucun compte serveur, aucune synchronisation cloud.",
      clearHistory: "Effacer l'historique",
      resetProfile: "Réinitialiser le profil",
      aboutTitle: "À propos",
      aboutDesc1:
        "Outil de candidature — analysez votre compatibilité ATS, refondez votre CV, rédigez des lettres personnalisées.",
      aboutDesc2: "Sortie FR/EN, 3 templates visuels, export PDF + DOCX, tout en local.",
    },
    upload: {
      loading: "Extraction en cours…",
      dragActive: "Déposez le fichier ici",
      idle: "Glissez votre CV ou cliquez pour parcourir",
      formats: "PDF, DOCX, TXT ou MD",
      loaded: "CV chargé et extrait",
    },
    kpis: {
      avgAts: "ATS moyen",
      sent: "Candidatures envoyées",
      interviewRate: "Taux d'entretien",
      companies: "Entreprises ciblées",
    },
    profile: {
      quickStartTitle: "Démarrage rapide",
      quickStartDesc:
        "Chargez un profil démo pour voir à quoi ressemble un profil complet, puis modifiez-le avec vos propres données. Tout est stocké localement dans votre navigateur. Aucune donnée n'est envoyée au serveur avant le lancement d'une analyse.",
      loadDemo: "Charger le profil démo",
      startFresh: "Repartir de zéro",
      exportJson: "Exporter JSON",
      importJson: "Importer JSON",
      identityTitle: "Identité",
      identityDesc:
        "Ces informations apparaissent dans l'en-tête de votre CV et la signature de votre lettre.",
      fullName: "Nom complet",
      jobTitle: "Titre / intitulé de poste",
      email: "Email",
      phone: "Téléphone",
      location: "Localisation",
      linkedin: "URL LinkedIn",
      pitchTitle: "Pitch & rôle principal",
      pitchDesc: "3–4 lignes. Utilisé par l'IA comme référence pour votre positionnement.",
      primaryRoleLabel: "Rôle principal actuel (ex : CEO chez Acme, Head of Growth chez X)",
      pitchLabel: "Pitch",
      experiencesTitle: "Expériences",
      experiencesDesc: "L'IA utilise jusqu'à 4 expériences. Marquez l'une comme rôle principal actuel.",
      addBtn: "Ajouter",
      experienceN: (n: number) => `Expérience #${n}`,
      primaryCurrent: "Rôle principal actuel",
      role: "Poste",
      company: "Entreprise",
      locationField: "Lieu",
      startYear: "Début (AAAA)",
      endYear: "Fin (AAAA ou vide)",
      bullets: "Points forts (4 idéal)",
      bulletPlaceholder: (n: number) => `Point ${n}`,
      noExp: "Aucune expérience. Cliquez sur « Ajouter » pour commencer.",
      educationTitle: "Formation",
      educationN: (n: number) => `Formation #${n}`,
      degree: "Diplôme",
      school: "École / Université",
      start: "Début",
      end: "Fin",
      certificationsTitle: "Certifications",
      certificationsDesc: "Séparées par des virgules.",
      skillsTitle: "Compétences",
      skillsDesc: "5 groupes recommandés.",
      addGroup: "Ajouter un groupe",
      groupName: "Nom du groupe",
      languagesTitle: "Langues",
      language: "Langue",
      level: "Niveau",
      achievementsTitle: "Banque de réalisations (optionnel)",
      achievementsDesc:
        "Un par ligne. L'IA les utilise pour enrichir les bullets quand vos expériences sont courtes.",
      toastDemoLoaded: "Profil démo chargé",
      toastCleared: "Profil réinitialisé",
      toastExported: "Profil exporté",
      toastImported: "Profil importé",
      toastInvalidJson: "Fichier JSON invalide",
    },
    history: {
      emptyTitle: "Historique vide",
      emptyDesc:
        "Lancez une analyse pour démarrer un historique de candidatures. Tout est stocké localement sur cette machine.",
      company: "Entreprise",
      job: "Poste",
      score: "Score",
      deleteBtn: "Supprimer",
    },
    toasts: {
      urlFetched: "Offre récupérée depuis l'URL",
      noCv: "Chargez d'abord votre CV.",
      noOffer: "Collez ou récupérez le texte de l'offre (>80 caractères).",
      analysisDone: "Analyse terminée — CV et lettre prêts.",
      analysisError: "Erreur d'analyse",
      exportError: "Erreur export",
    },
    // ATS panel (already mostly French — kept for completeness)
    ats: {
      scoresTitle: "Scores ATS",
      scoresDesc: "Compatibilité CV ↔ offre, mesurée sur 5 dimensions.",
      overallLabel: "Score global",
      keywordsLabel: "Mots-clés",
      experienceLabel: "Expérience",
      skillsLabel: "Compétences",
      atsLabel: "ATS-safe",
      compatTitle: "Compatibilité ATS par système",
      compatDesc: "Estimation par moteur ATS de marché.",
      radarTitle: "Cartographie des dimensions",
      radarDesc: "Vue radar du fit.",
      coveredTitle: "Couvert",
      coveredDesc: "Ce que l'offre demande et que votre profil couvre.",
      gapsTitle: "À combler",
      gapsDesc: "Écarts détectés entre offre et profil — déjà reformulés dans le CV.",
      optimizationsTitle: "Optimisations appliquées",
      optimizationsDesc: "Liste des optimisations effectuées automatiquement.",
      vigilanceLabel: "Vigilance",
      priorityKeywords: "Mots-clés ATS prioritaires",
      hardSkills: "Hard skills",
      softSkills: "Soft skills",
      toolsTech: "Outils & technologies",
      certifications: "Certifications attendues",
      experienceLevel: "Niveau d'expérience demandé",
      missingSkills: "Compétences manquantes",
      missingKeywords: "Mots-clés absents",
      toReframe: "À reformuler",
      titleSuggestions: "Titres de poste suggérés",
      parsingIssues: "Problèmes de parsing",
      weakSections: "Sections ATS faibles",
    },
  },

  en: {
    nav: {
      new: "New application",
      ats: "ATS analysis",
      cv: "My CV",
      letter: "My letter",
      history: "History",
      profile: "My profile",
      settings: "Settings",
    },
    brand: "CV + cover letter AI",
    footer: {
      version: "Version 1.0 · Privacy first",
      privacy:
        "Your data is processed locally. No personal information is transmitted or stored.",
      contact: "Contact us",
    },
    viewTitles: {
      new: "New application",
      ats: "ATS analysis",
      cv: "My CV",
      letter: "My letter",
      history: "Application history",
      settings: "Settings",
      profile: "My profile",
    },
    profileWarning: {
      title: "Set up your profile first",
      desc: "The analysis quality depends on it. Click",
      link: "My profile",
      desc2: "to load the demo or build your own.",
    },
    newApp: {
      step1Title: "1. Your CV",
      step1Desc: "PDF, DOCX, TXT. You can also use your current CV.",
      step2Title: "2. Job offer",
      step2Desc: "Paste the job offer text, or provide a URL.",
      urlPlaceholder: "https://… (LinkedIn, Indeed, Glassdoor…)",
      fetchBtn: "Fetch",
      offerPlaceholder: "Or paste the job offer text directly…",
      charCount: (n: number) => `${n} characters${n >= 80 ? " ✓" : " (min. 80)"}`,
      step3Title: "3. Target & tone",
      step3Desc: "Output language, company, LinkedIn, CV tone and letter tone.",
      outputLangLabel: "CV and cover letter language",
      outputLangDescFr: "CV et lettre en français naturel, titres de sections en français.",
      outputLangDescEn:
        "CV and cover letter will be written in fluent English, with native Anglo style and section titles.",
      targetCompanyLabel: "Target company",
      targetCompanyPlaceholder: "e.g. Datadog, Stripe, McKinsey…",
      linkedinLabel: "Your LinkedIn URL (optional)",
      linkedinPlaceholder: "https://www.linkedin.com/in/your-handle",
      cvVersionLabel: "CV version",
      letterToneLabel: "Letter tone",
      launchBtn: "Run ATS + CV + cover letter analysis",
      launchBtnShort: "Run analysis",
      analyzing: "Analyzing…",
      analyzingShort: "Analyzing…",
      estimatedTime: "~20 seconds • ATS + rewritten CV + cover letter + coach",
      newAnalysis: "New analysis",
      badgeCv: (ready: boolean) => `CV ${ready ? "✓" : "—"}`,
      badgeOffer: (ready: boolean, n: number) => `Offer ${ready ? "✓" : `${n}/80`}`,
    },
    empty: {
      ats: "Run an analysis to see your ATS scores.",
      cv: "No CV generated yet.",
      letter: "No cover letter generated yet.",
      startBtn: "Start an analysis",
    },
    cvView: {
      tonalityLabel: "Tone",
      onePage: "· A4 single page",
      templateTitle: "Visual template",
      templateDesc: "All templates are single column and ATS safe.",
    },
    letterView: {
      tonLabel: "Tone",
    },
    settings: {
      storageTitle: "Storage",
      storageDesc:
        "Everything is stored locally in your browser. No server-side account, no cloud sync.",
      clearHistory: "Clear application history",
      resetProfile: "Reset profile to empty",
      aboutTitle: "About",
      aboutDesc1:
        "Job application tool — analyze ATS fit, regenerate CV, draft personalized cover letters.",
      aboutDesc2: "FR/EN output, 3 visual templates, PDF + DOCX export, all client-side.",
    },
    upload: {
      loading: "Extracting…",
      dragActive: "Drop the file here",
      idle: "Drag your CV here or click to browse",
      formats: "PDF, DOCX, TXT or MD",
      loaded: "CV loaded and extracted",
    },
    kpis: {
      avgAts: "Avg. ATS score",
      sent: "Applications sent",
      interviewRate: "Interview rate",
      companies: "Companies targeted",
    },
    profile: {
      quickStartTitle: "Quick start",
      quickStartDesc:
        "Load a demo profile to see what a complete one looks like, then edit it with your own data. Everything is stored locally in your browser. Nothing is sent to any server until you launch an analysis.",
      loadDemo: "Load demo profile",
      startFresh: "Start fresh",
      exportJson: "Export JSON",
      importJson: "Import JSON",
      identityTitle: "Identity",
      identityDesc: "These details appear in your CV header and letter signature.",
      fullName: "Full name",
      jobTitle: "Job title / headline",
      email: "Email",
      phone: "Phone",
      location: "Location",
      linkedin: "LinkedIn URL",
      pitchTitle: "Pitch & primary role",
      pitchDesc: "3–4 lines. Used by the AI as the source of truth for your positioning.",
      primaryRoleLabel: "Primary current role (e.g. CEO of Acme, Head of Growth at X)",
      pitchLabel: "Pitch",
      experiencesTitle: "Experiences",
      experiencesDesc: "The AI uses up to 4 experiences. Mark one as primary current role.",
      addBtn: "Add",
      experienceN: (n: number) => `Experience #${n}`,
      primaryCurrent: "Primary current role",
      role: "Role",
      company: "Company",
      locationField: "Location",
      startYear: "Start (YYYY)",
      endYear: "End (YYYY or empty)",
      bullets: "Bullets (4 ideal)",
      bulletPlaceholder: (n: number) => `Bullet ${n}`,
      noExp: 'No experience yet. Click "Add" to start.',
      educationTitle: "Education",
      educationN: (n: number) => `Education #${n}`,
      degree: "Degree",
      school: "School",
      start: "Start",
      end: "End",
      certificationsTitle: "Certifications",
      certificationsDesc: "Comma separated.",
      skillsTitle: "Skills",
      skillsDesc: "5 groups recommended.",
      addGroup: "Add group",
      groupName: "Group name",
      languagesTitle: "Languages",
      language: "Language",
      level: "Level",
      achievementsTitle: "Achievements bank (optional)",
      achievementsDesc:
        "One per line. The AI uses these to enrich bullets when your experiences are short.",
      toastDemoLoaded: "Demo profile loaded",
      toastCleared: "Profile cleared",
      toastExported: "Profile exported",
      toastImported: "Profile imported",
      toastInvalidJson: "Invalid JSON file",
    },
    history: {
      emptyTitle: "Empty history",
      emptyDesc:
        "Run an analysis to start tracking applications. Everything is stored locally on this machine.",
      company: "Company",
      job: "Position",
      score: "Score",
      deleteBtn: "Delete",
    },
    toasts: {
      urlFetched: "Job offer fetched from URL",
      noCv: "Please load your CV first.",
      noOffer: "Paste or fetch the job offer text (>80 characters).",
      analysisDone: "Analysis complete — CV and cover letter ready.",
      analysisError: "Analysis error",
      exportError: "Export error",
    },
    ats: {
      scoresTitle: "ATS Scores",
      scoresDesc: "CV ↔ job offer fit, measured on 5 dimensions.",
      overallLabel: "Overall score",
      keywordsLabel: "Keywords",
      experienceLabel: "Experience",
      skillsLabel: "Skills",
      atsLabel: "ATS-safe",
      compatTitle: "ATS compatibility by system",
      compatDesc: "Estimated score per market ATS engine.",
      radarTitle: "Dimensions map",
      radarDesc: "Radar view of your fit.",
      coveredTitle: "Covered",
      coveredDesc: "What the offer requires and your profile covers.",
      gapsTitle: "Gaps",
      gapsDesc: "Detected gaps between offer and profile — already rewritten in your CV.",
      optimizationsTitle: "Applied optimizations",
      optimizationsDesc: "List of optimizations automatically applied.",
      vigilanceLabel: "Watch out",
      priorityKeywords: "Priority ATS keywords",
      hardSkills: "Hard skills",
      softSkills: "Soft skills",
      toolsTech: "Tools & technologies",
      certifications: "Expected certifications",
      experienceLevel: "Required experience level",
      missingSkills: "Missing skills",
      missingKeywords: "Missing keywords",
      toReframe: "To reframe",
      titleSuggestions: "Suggested job titles",
      parsingIssues: "Parsing issues",
      weakSections: "Weak ATS sections",
    },
  },
} as const;

export type UIStrings = typeof UI["fr"];
